name = "SpinTests"
uuid = "361d196f-5a68-406c-81fd-16864870ccd4"
authors = ["James <gholamja@cardiff.ac.uk> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
